name: four_elt
description: HideAndSeek

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.3
  collection: ^1.15.0
  screen_brightness: ^0.1.1
  equatable: ^2.0.3
  extended_nested_scroll_view: ^5.0.0
  freezed_annotation: ^0.15.0

  #provider: ^6.0.1
  #bloc: ^7.2.1
  #flutter_bloc: ^7.3.1
  #bloc_concurrency: ^0.1.0

  #auto_route: ^3.2.4

  #firebase_analytics: ^8.3.4
  #firebase_crashlytics: ^2.2.4
  #permission_handler: ^8.2.5
  #url_launcher: ^6.0.12
  #visibility_detector: ^0.2.2
  #animations: ^2.0.2
  #share_plus: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  freezed: ^0.15.0+1
  json_serializable: ^5.0.2
  #auto_route_generator: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
